### ISSUE TITLE
Issue beta multivector Kalman filter

### ISSUE THREAD

**Issue by Simone40** [MattCocci/DSGE#1]
Hi, I have seen you use the Kalman filter by Dr. Karibzhanov following path: DSGE/kalman/kalcvf2NaN.m (in the documentation http://karibzhanov.com/help/kalcvf.htm b should be allowed to be a matrix N_y x T (+ leads)). 

However if a matrix is given (as b term) the output is an error that b should be a column vector.

in my (humble) opinion it could be fix by suppressing lines from 87 to 89 and in line 162 
replacing
`dy = data(:,t)-H*z-b`
with
`
   dy = data(:,t)-H*z-b(:,t);`

What do you think?

**Comment by MattCocci** [comment]
The documentation at http://karibzhanov.com/help/kalcvf.htm refers to a generalized version of the function that Dr. Karibzhanov produced separately (and not in this repo) that explicitly allows for time-varying parameter vectors/matrices a, b, F, H.

The code at DSGE/kalman/kalcvf2NaN.m assumes _non_-time-varying parameter vectors/matrices---a, b, F, H constant throughout.

The fix you suggested definitely would/should be part of a generalized function (like the one described in the documentation you linked to) that allows for time-varying parameter vectors/matrices.

However, in the simplified program at DSGE/kalman/kalcvf2NaN.m (which assumes those things are constant), I think it makes sense to leave b as just a column vector.

**Comment by Simone40** [comment]
Perfect, thanks a lot.
